# 应用名称
spring:
  application:
      name: zuul-server
# 应用服务 WEB 访问端口
server:
  port: 8770
eureka:
  client:
     service-url:
       defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    producter-client1:
      path: /producter-client1/**
      service-id: eureka-producter
#开启查看路由的端点
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
