# 应用名称
spring:
  application:
      name: zuul-server
# 应用服务 WEB 访问端口
server:
  port: 8770
eureka:
  client:
     service-url:
       defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    producter-client1:
      path: /producter-client1/**
      service-id: eureka-producter
      #url: http://127.0.0.1:8081/  #把包含path中的路径的请求跳转到url对应地址
      #service-id: eureka-producter   #把包含path中的路径的请求跳转到对应服务
#开启查看路由的端点
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
